其他

diff --git a/icadown b/icadown
--- a/icadown
+++ b/icadown
@@ -34,6 +34,7 @@ available PKes:
     keepalived        to download package of keepalived
     maven             to download package of maven
     jdk               to download package of jdk
+    kafka             to download package of kafka
 examples:
     ./ezdown -P mysql
 EOF
@@ -184,6 +185,22 @@ function download_maven() {
   fi
 }
 
+function download_kafka() {
+  KAFKA_URL="https://archive.apache.org/dist/kafka/${kafka_version}/kafka_2.13-${kafka_version}.tgz"
+
+  if [[ -f "$BASE/kafka_2.13-${kafka_version}.tgz" ]];then
+    logger warn "kafka binaries already existed"
+  else
+    logger info "downloading kafka binaries, arch:$ARCH, version:${kafka_version}"
+    if [[ -e /usr/bin/wget ]];then
+      wget -c --no-check-certificate "$KAFKA_URL" || { logger error "downloading kafka failed"; exit 1; }
+    else
+      curl -k -C- -O --retry 3 "$KAFKA_URL" || { logger error "downloading kafka failed"; exit 1; }
+    fi
+    mv -f "./kafka_2.13-${kafka_version}.tgz" "$BASE/"
+  fi
+}
+
 function download_all() {
   download_mysql && \
   download_docker && \
@@ -191,7 +208,8 @@ function download_all() {
   download_nginx && \
   download_keepalived && \
   download_jdk && \
-  download_maven
+  download_maven && \
+  download_kafka
 }
 
 ### Main Lines ##################################################
@@ -218,7 +236,7 @@ function main() {
           ACTION="download_all"
           ;;
         P)
-          [[ $OPTARG =~ (mysql|docker|zookeeper|nginx|keepalived|maven|jdk) ]] || \
+          [[ $OPTARG =~ (mysql|docker|zookeeper|nginx|keepalived|jdk|maven|kafka) ]] || \
           { usage-down-packages; exit 1; }
           ACTION="download_$OPTARG"
           ;;
